services:
  web:
    build:
      context: ./franklincce
      dockerfile: Dockerfile.prod
    command: gunicorn franklincce.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - type: volume
        source: static_volume
        target: /home/app/web/staticfiles
      - type: bind
        source: ./db.sqlite3
        target: /home/app/web/db.sqlite3
    expose:
      - 8000
    env_file:
      - ./.env.prod
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web
volumes:
  static_volume:
  db_persist:
