version: '3.8'

services:
  web:
    build: ./franklincce
    command: gunicorn franklincce.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./franklincce/:/usr/src/franklincce
    ports:
      - 8000:8000
