# Generated by Django 4.2.12 on 2024-06-19 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegislationBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference_type', models.CharField(choices=[('M', 'Middle School'), ('H', 'High School')], default='H', max_length=1)),
                ('pdf', models.FileField(upload_to='uploads/')),
                ('name', models.CharField(max_length=256)),
                ('import_strategy', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='LegislativeText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assembly', models.CharField(choices=[('RGA', 'Red General Assembly'), ('BGA', 'Blue General Assembly'), ('WGA', 'White General Assembly'), ('RHB', 'Red House'), ('BHB', 'Blue House'), ('WHB', 'White House'), ('RSB', 'Red Senate'), ('BSB', 'Blue Senate'), ('WSB', 'White Senate'), ('SEN', 'Senate'), ('HOU', 'House'), ('GEN', 'General Assembly')], default='GEN', max_length=3)),
                ('text', models.TextField()),
                ('year', models.IntegerField()),
                ('committee', models.IntegerField()),
                ('docket_order', models.IntegerField()),
                ('school', models.CharField(max_length=256)),
                ('sponsors', models.CharField(max_length=256)),
                ('from_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explorer.legislationbook')),
            ],
        ),
    ]
