# Generated by Django 4.2.12 on 2024-06-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legislativetext',
            name='legislation_title',
            field=models.CharField(default='Sample title', max_length=512),
            preserve_default=False,
        ),
    ]
