# Generated by Django 4.2.14 on 2024-07-24 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='legislativetext',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explorer.category'),
        ),
    ]
