# Generated by Django 4.2.12 on 2024-06-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0003_legislationbook_has_performed_export_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegislationClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of this classification.', max_length=256)),
                ('text_to_match', models.CharField(help_text='a comma seperated list of keywords to include in the classification. spaces and dashes are discluded.', max_length=256)),
            ],
        ),
    ]
