# Generated by Django 4.2.12 on 2024-06-28 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0005_legislationclassification_obvious_change'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legislationclassification',
            name='obvious_change',
        ),
    ]
