# Generated by Django 4.2.12 on 2024-06-30 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0006_remove_legislationclassification_obvious_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='legislativetext',
            name='category',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='legislativetext',
            name='country',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
